apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: replicas-patch.yaml
  - path: resources-patch.yaml

images:
  - name: ghcr.io/ryuzon07/raftweave
    newTag: develop                    # staging always runs develop branch image
  - name: ghcr.io/ryuzon07/raftweave-dashboard
    newTag: develop
