apiVersion: v1
kind: ServiceAccount
metadata:
  name: raftweave
  namespace: raftweave
  labels:
    app.kubernetes.io/name: raftweave
    app.kubernetes.io/managed-by: kustomize
  annotations:
    # AWS IRSA annotation — populated in production overlay
    eks.amazonaws.com/role-arn: ""
