apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namePrefix: staging-
namespace: raftweave-staging
patches:
  - target:
      kind: Deployment
      name: raftweave-auth
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
