apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: raftweave-postgres
  namespace: raftweave
  labels:
    app.kubernetes.io/name: raftweave
    app.kubernetes.io/component: postgres
    app.kubernetes.io/managed-by: kustomize
spec:
  serviceName: raftweave-postgres
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: raftweave
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: raftweave
        app.kubernetes.io/component: postgres
    spec:
      securityContext:
        runAsUser: 999           # postgres user
        fsGroup: 999
      terminationGracePeriodSeconds: 60
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_DB
              value: "raftweave"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: raftweave-postgres
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: raftweave-postgres
                  key: password
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - raftweave
                - -d
                - raftweave
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - raftweave
                - -d
                - raftweave
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
        labels:
          app.kubernetes.io/name: raftweave
          app.kubernetes.io/component: postgres
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
