apiVersion: v1
kind: Service
metadata:
  name: raftweave-consensus
  namespace: raftweave
  labels:
    app.kubernetes.io/name: raftweave
    app.kubernetes.io/component: consensus
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: raftweave
    app.kubernetes.io/component: consensus
  ports:
    - name: api
      port: 80
      targetPort: api
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
