apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: replicas-patch.yaml
  - path: resources-patch.yaml

images:
  - name: ghcr.io/ryuzon07/raftweave
    newTag: v1.0.0                     # production always runs a pinned semantic version
  - name: ghcr.io/ryuzon07/raftweave-dashboard
    newTag: v1.0.0
